version: '3.8'
services:
  pgsql:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sermonindex_local
    ports: [5432:5432]
    command: postgres
